### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by dongxuyue** [Picsart-AI-Research/HD-Painter#1]
Hello, great work! I am eager to know when the code will be released as I can't wait to try it out.

**Comment by kelisiya** [comment]
+1

**Comment by CyberTimon** [comment]
+1

**Comment by AndranikSargsyan** [comment]
We will release the code on GItHub soon. Meanwhile, you can try our Hugging Face demo https://huggingface.co/spaces/PAIR/HD-Painter

**Comment by luonghuuthanhnam** [comment]
+1

**Comment by MahdiMohseni0033** [comment]
+1

**Comment by AndranikSargsyan** [comment]
Thank you for your interest. We have released the code.

**Comment by rahulsimran6969** [comment]
demo not working, runtime error.

**Comment by AndranikSargsyan** [comment]
@rahulsimran6969 Thank you for your comment. We fixed the demo. It is back to live on HF.
