### ISSUE TITLE
encounting a wierd issue

### ISSUE THREAD

**Issue by ThisRookie** [Picsart-AI-Research/HD-Painter#13]
TypeError: event_trigger() got an unexpected keyword argument '_js'

**Comment by ThisRookie** [comment]
demo.load(_js=js_str)

**Comment by AndranikSargsyan** [comment]
Hello. What is the version of Gradio you are using? If it's different than version `3.47.1` , please try reinstalling Gradio by running 
```
pip install gradio==3.47.1
```

**Comment by ThisRookie** [comment]
> Hello. What is the version of Gradio you are using? If it's different than version `3.47.1` , please try reinstalling Gradio by running
> 
> ```
> pip install gradio==3.47.1
> ```

The solution works for my case, thank you!
